import { TTicket } from '../../../types';

const getMinutesActive = ({ minutesToSubtract }: { minutesToSubtract: number }) =>
	new Date(new Date().setTime(new Date().getTime() - minutesToSubtract * 60 * 1000)).toISOString();

const tickets: TTicket[] = [
	{
		id: 1,
		trackNo: '1001',
		ticketValue: 'A12',
		serviceName: 'Кредиты, карты, счета, другие сервисы',
		startTime: getMinutesActive({ minutesToSubtract: 32.55 }),
		status: 0,
		window: null,
		workStation: '992',
		confirmTime: null,
		employee: null,
		segmentId: null,
	},
	{
		id: 2,
		trackNo: '1002',
		ticketValue: 'A16',
		serviceName: 'Инвестиции, сбережения, страхование',
		startTime: getMinutesActive({ minutesToSubtract: 24.67 }),
		status: 1,
		window: null,
		workStation: '993',
		confirmTime: null,
		employee: null,
		segmentId: null,
	},
	{
		id: 3,
		trackNo: '1003',
		ticketValue: 'A21',
		serviceName: 'Кредиты, карты, счета, другие сервисы',
		startTime: getMinutesActive({ minutesToSubtract: 9.23 }),
		status: 2,
		window: null,
		workStation: '994',
		confirmTime: null,
		employee: null,
		segmentId: null,
	},
	{
		id: 4,
		trackNo: '1004',
		ticketValue: 'A22',
		serviceName: 'Инвестиции, сбережения, страхование',
		startTime: getMinutesActive({ minutesToSubtract: 7.44 }),
		status: 2,
		window: null,
		workStation: '995',
		confirmTime: null,
		employee: null,
		segmentId: null,
	},
	{
		id: 5,
		trackNo: '1005',
		ticketValue: 'A23',
		serviceName: 'Касса',
		startTime: getMinutesActive({ minutesToSubtract: 6.9 }),
		status: 2,
		window: null,
		workStation: '996',
		confirmTime: null,
		employee: null,
		segmentId: null,
	},
	{
		id: 6,
		trackNo: '1006',
		ticketValue: 'A24',
		serviceName: 'Кредиты, карты, счета, другие сервисы',
		startTime: getMinutesActive({ minutesToSubtract: 6.23 }),
		status: 2,
		window: null,
		workStation: '996',
		confirmTime: null,
		employee: null,
		segmentId: null,
	},
	{
		id: 7,
		trackNo: '1007',
		ticketValue: 'A37',
		serviceName: 'Кредиты, карты, счета, другие сервисы',
		startTime: getMinutesActive({ minutesToSubtract: 5.3 }),
		status: 2,
		window: 7,
		workStation: '997',
		confirmTime: getMinutesActive({ minutesToSubtract: 1 }),
		segmentId: '1',
		employee: {
			id: '2',
			employeeName: 'Плотникова Маргарита',
			position: 'Кассир',
			isActive: false,
			timeBeingInactive: '1',
			timeBeingActive: null,
			segmentId: '1',
			// timeBeingActive: null,
		},
	},
];

export default tickets;
